### ISSUE TITLE
Discussion: replace shelljs

### ISSUE THREAD

**Issue by DanielRuf** [runebaas/git-identity#2]
git-identity mainly uses the `exec` method.
I think we can replace this with `child_process.exec/execSync`.

https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options

https://github.com/runebaas/git-identity/blob/9271429aae9170bff2860c15e485234c47c5a3cd/src/main.js

https://github.com/shelljs/shelljs/blob/master/src/exec.js#L210
https://github.com/shelljs/shelljs/blob/master/src/exec.js#L19
https://github.com/shelljs/shelljs/blob/master/src/exec.js#L60

From the NodeJS docs for child_process:
> Use the { stdio: 'ignore' } option if the output will not be consumed.

> 'ignore' - Instructs Node.js to ignore the fd in the child. While Node.js will always open fds 0 - 2 for the processes it spawns, setting the fd to 'ignore' will cause Node.js to open /dev/null and attach it to the child's fd.

`windowsHide` may be also useful:
> windowsHide <boolean> Hide the subprocess console window that would normally be created on Windows systems. Default: false.

**Comment by runebaas** [comment]
It uses the `which` command. Shell.js takes care of the cross platform differences that exists there.

I'm very hesitant to replace `which` with something else or implement it myself, so why not use all the edge cases that the shell.js developers considered with `exec` too?

**Comment by DanielRuf** [comment]
`which` can be directly used. See https://www.npmjs.com/package/which (used by shelljs).
