### ISSUE TITLE
Unsetting signingkey does not work when globally set

### ISSUE THREAD

**Issue by DanielRuf** [runebaas/git-identity#7]
When the signing key is unset the global setting is used and overrides the local setting.

https://github.com/runebaas/git-identity/blob/master/src/main.js#L44

Setting it to `""` might be better.

Also take care of `tag.forcesignannotated=true` and `commit.gpgsign=true`.

**Comment by runebaas** [comment]
That's a fun edge case, thanks for noticing! I'll come fix it in the coming days

**Comment by runebaas** [comment]
It's fixed (fb1a539128e97551c22fd96609b4fcc2310a0c93), if there is no signing key in the profile, it'll set the `core.gpgsign` to `false` in the directory.

Setting it to just `""` or `" "` will cause an error with `gpg` and prevent you from committing
